/*
* @author 黄伟
* @date 2017/11/29
*/

export const GET_ADVICE_RABTLIST_TABLE = 'GET_ADVICE_RABTLIST_TABLE'
export const GET_ADVICE_LEFTLIST_TABLE = 'GET_ADVICE_LEFTLIST_TABLE'
export const GET_ADVICE_SEARCH_TABLE = 'GET_ADVICE_SEARCH_TABLE'
export const GET_ADVICE_AMEND_TABLE = 'GET_ADVICE_AMEND_TABLE'
export const GET_ADVICE_DELETE_TABLE = 'GET_ADVICE_DELETE_TABLE'
export const GET_ADVICE_ADD_TABLE = 'GET_ADVICE_ADD_TABLE'
export const GET_ADDLEFTLIST_AMEND_TABLE = 'GET_ADDLEFTLIST_AMEND_TABLE'

