export const SET_ACCOUNT_LIST = 'setAccountList'
export const SET_STAFF_LIST = 'setStaffList'
export const RESET = 'reset'
export const SET_TOTAL = 'setTotal'
export const OPEN_PAGE = 'openPage'
export const SET_CURRENT_PAGE_NAME = 'setCurPageName'
